# Generated by Django 2.1.2 on 2018-10-30 11:33

from django.db import migrations
from products.models import Product
import json


def create_default_products(apps, schema_editor):
    with open('products/data/products.json', 'r') as file:
        context = json.load(file)

    for product in context['products']:
        new_product = Product(
            name=product['name'],
            title=product['title'],
            alt=product['alt'],
            description=product['description'],
            characteristics=product['characteristics'],
            details=product['details'],
        )
        new_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181026_0827'),
    ]

    operations = [
        migrations.RunPython(
            create_default_products,
            lambda x, y: (x, y)
        )
    ]
