# Generated by Django 2.1.2 on 2018-10-30 11:33

from django.db import migrations
from products.models import Product, Category
from images.models import Image
import json


def create_default_products(apps, schema_editor):
    with open('products/data/products.json', 'r') as file:
        context = json.load(file)

    categories = []

    for product in context['products']:
        if product['category'] not in categories:
            categories.append(product['category'])
            query = Category.objects.filter(title=product['category']).count()
            if not query:
                new_category = Category(title=product['category'])
                new_category.save()
        new_product = Product(
            name=product['name'],
            title=product['title'],
            alt=product['alt'],
            description=product['description'],
            characteristics=product['characteristics'],
            details=product['details'],
            image=Image.objects.get(title='default'),
            url_key=product['url_key'],
            category=Category.objects.get(title=product['category']),
        )
        new_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181030_1228'),
    ]

    operations = [
        migrations.RunPython(
            create_default_products,
            lambda x, y: (x, y)
        )
    ]
