# Generated by Django 2.1.2 on 2018-10-30 10:16

from django.db import migrations, models
from django.core.files import File


def create_default_image(apps, schema_editor):
    file_name = 'default.png'
    Image = apps.get_model('images', 'image')

    img = Image.objects.create(
        title='default',
        value=file_name
    )
    img.value.save(
        file_name,
        File(
            open('images/fixtures/images/default.png', 'rb')
        )
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('value', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RunPython(
            create_default_image,
            lambda x, y: (x, y)
        ),
    ]
